name: aws_s3_upload_lite
description: Amazon S3 is an object storage service that stores data as objects within buckets. aws_s3_upload_lite is a simple, convenient package for uploading files to AWS S3 buckets.
version: 0.1.4
homepage: https://github.com/Yoda-Man/aws_s3_upload_lite

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  amazon_cognito_identity_dart_2: ^3.6.5
  http: ^1.2.2
  path: ^1.9.0
  recase: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
